
FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npx prisma generate
RUN npm run build
RUN npm prune --production

EXPOSE 5000

CMD ["node", "dist/server.js"]

